
import random
import functions

""" Screen time data """
screen_time = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "snapchat", "snapchat", "snapchat", "snapchat", "snapchat",
"snapchat", "snapchat", "snapchat", "snapchat", "snapchat", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "gmail", "gmail", "gmail", "gmail", "gmail", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "snapchat", "snapchat", "", "", "", "", "", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom",
"zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "zoom", "",
"", "", "", "", "", "", "", "snapchat", "", "", "", "", "", "", "notion",
"notion", "notion", "notion", "notion", "notion", "notion", "notion",
"notion", "notion", "notion", "notion", "notion", "notion", "notion",
"chrome", "chrome", "chrome", "chrome", "chrome", "chrome", "chrome",
"chrome", "chrome", "chrome", "chrome", "chrome", "chrome", "chrome",
"chrome", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "youtube",
"youtube", "youtube", "youtube", "youtube", "youtube", "youtube",
"youtube", "youtube", "youtube", "youtube", "youtube", "youtube",
"youtube", "youtube", "youtube", "youtube", "youtube", "youtube",
"youtube", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "goodnotes", "goodnotes", "goodnotes",
"goodnotes", "goodnotes", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "khan_academy", "khan_academy", "khan_academy",
"khan_academy", "khan_academy", "khan_academy", "khan_academy",
"khan_academy", "khan_academy", "khan_academy", "khan_academy",
"khan_academy", "khan_academy", "khan_academy", "khan_academy",
"khan_academy", "khan_academy", "khan_academy", "khan_academy",
"khan_academy", "", "", "", "", "", "", "", "", "", "", "chrome", "chrome",
"chrome", "chrome", "chrome", "chrome", "chrome", "chrome", "chrome",
"chrome", "chrome", "chrome", "chrome", "chrome", "chrome", "chrome",
"chrome", "chrome", "chrome", "chrome", "chrome", "chrome", "chrome",
"chrome", "chrome", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "snapchat", "snapchat",
"snapchat", "snapchat", "snapchat", "snapchat", "snapchat", "snapchat",
"snapchat", "snapchat", "snapchat", "snapchat", "snapchat", "snapchat",
"snapchat", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "snapchat",
"snapchat", "snapchat", "snapchat", "snapchat", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "netflix", "netflix",
"netflix", "netflix", "netflix", "netflix", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "snapchat", "snapchat", "snapchat",
"snapchat", "snapchat", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify",
"spotify", "spotify", "spotify", "spotify", "spotify", "spotify", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "tiktok",
"tiktok", "tiktok", "tiktok", "tiktok", "tiktok", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]